permalink: /:year/:month/:day/:title
markdown: kramdown
highlighter: rouge
mathjax: disabled
lang: zh-CN

sass:
  style: compressed
# 作者信息
author:
  name: 360武汉云安全团队
  email: dejavuzhou@qq.com
  link: http://captcha.mojotv.cn
  weibo: http://weibo.com/u/2706451481?is_all=1
  github: http://github.com/libragen

# 站点信息
title: 360武汉云安全团队
description: 技术分享
url: https://360cs.github.io/
rss_url: /pages/atom.xml
comment_api: https://felix.mojotv.cn

# avatar头像及Favicon
avatar: /assets/image/logo.jpg
favicon: /assets/image/logo.jpg
logo: /assets/image/logo.jpg

# Jekyll Plugin
# https://help.github.com/articles/adding-jekyll-plugins-to-a-github-pages-site/
plugins:

# 定义你的分类
categories: Vuejs React Golang Python Docker Kubernetes Algorithm

# 排除文件夹
exclude: [install.sh,jekyll.sh,Gemfile,Gemfile.lock,jekyll_run.sh]

# 谷歌统计ID
ga_id: UA-129013660-5

# google adsense ID
gad_id: ca-pub-6269173703140859

webmaster_verifications:
  google: 1234
  bing: F71F639CAE579E63E44E43522ADED67F
  alexa: 1234
  yandex: 1234
  baidu: nDKgkSQxIO
  360: 4f66b4f11f2ba5c4a48abf000c5e5cbd

twitter:
  username: neochau
  card: summary

facebook:
  app_id: 1234
  publisher: 1234
  admins: 1234

social:
  name: 360武汉云安全团队
  links:
    - https://twitter.com/neochau
    - https://github.com/libragen
    - https://github.com/mojocn
    - https://github.com/JJJJJJJerk
    - https://weibo.com/dejavuzhou/home
    - http://captcha.mojotv.cn
